extends SceneTree
func _initialize() -> void:
	var kits = load("res://scripts/kits.gd")
	var text := "# Class abilities\n\nCurrent implementation, September 8, 2026. Balance is provisional and needs human playtesting. Fulcrum has thirteen abilities (Starfall on Shift+6); other classes have twelve: 1–7 on the first bar and Shift+1–5 on the second. All slots can be rebound or moved in Edit HUD. Older layouts automatically gain missing abilities in empty slots.\n\n"
	for champion in kits.NAMES:
		text += "## " + champion + "\n\n| Key | Ability | Effect | Cast | Cooldown |\n| --- | --- | --- | --- | --- |\n"
		var kit: Array = kits.get_kit(champion)
		for i in range(kit.size()):
			var s: Dictionary = kit[i]
			text += "| %s | %s | %s | %s | %ss%s |\n" % [str(i + 1) if i < 7 else "Shift+" + str(i - 6), s.name, kits.summary(s), "Instant" if s.cast == 0 else str(s.cast) + "s", s.cd, " (off GCD)" if s.off else ""]
		text += "\n"
	text += "## Shared rules\n\nHeat, Resolve and Meditation cap at 100. Graviton DoT ticks generate 5 Meditation each second for up to 8s. A successful Collapse grants one instant Graviton, retained until used. At 75+ Meditation Collapse stuns for 3s (subject to DR) without spending resource. Starfall requires 50+ and consumes all Meditation only on successful completion, dealing 20 + 0.4 per point. Completed DPS Mend clears all attached DoTs; standing in a ground hazard still deals damage. Each Luminary owns at most three stars. Brands, stars, anchors, defensive states, roots and ground fields are authoritative and replicated. Class resources reset between rounds and at duel boundaries. Stars expire after 30 seconds; brands after 10.\n\nGravity Anchor is placed up to 10m in the direction faced, swept against terrain and projected onto the floor. It lasts 20s. Anchor abilities need the caster within 28m. Inward and Outward also require anchor-to-target range. Inward, Outward, Collapse and Heavy Orbit ignore line-of-sight blockers; pushes and pulls still stop at solid collision. Non-anchor ground effects still require line of sight. Counterweight exchanges immediately after validation; both swept routes must be clear.\n\nStuns, disorients, and roots share diminishing returns. Solar Flare breaks on damage. Rooted characters can cast but cannot jump or use movement abilities; Absolution clears roots and slows. Hold the Line prevents movement and displacement but allows turning; attacking ends it. Damage reductions use the strongest applicable reduction, not multiplication.\n\nLast Light prevents one lethal hit by leaving 1 HP; it is not a resurrection. Intercede redirects at most 30 raw damage, requires ongoing range and line of sight, and cannot form recursive damage chains. Mend always heals up to 28, without dampening. Other healing retains match dampening in arena matches only; world healing is never dampened.\n\nWorld bystanders cannot damage, control, or displace duelists, or heal/protect/exchange places with them. Self abilities remain available. Bot priorities exercise each identity; they are introductory sparring AI, not a competitive benchmark.\n\nAnchor rings and timers, burning-field outlines, Supernova warnings, resource text, brand counts, star counts, and status icons expose combat state. Earthsplitter applies a brief stun with a small airborne launch. Exact character transformation animations, sound, and bespoke spell cinematics are not implemented by this class pass.\n"
	FileAccess.open("res://docs/CLASS_ABILITIES.md", FileAccess.WRITE).store_string(text)
	quit()
